In [6]:
import numpy as np
size = int(input())
size2 = int(size/2)
A = np.round(np.random.random((size,size)),2)
B = np.zeros((size2,size2))
for i in range(size2):
    for j in range(size2):
        B[i][j] = np.amax(A[i*2:i*2+2,j*2:j*2+2]) 
print(A)
print(B)


4
[[0.88 0.48 0.88 0.58]
 [0.87 0.3  0.63 0.1 ]
 [0.85 0.37 0.89 0.  ]
 [0.44 0.27 0.42 0.13]]
[[0.88 0.88]
 [0.85 0.89]]
